; 24x21 C64 sprite: Smiley face
; Each byte is a row, leftmost bit is leftmost sprite pixel

.byte $ff, $ff, $ff
.byte $ff, $ff, $ff
.byte $ff, $ff, $ff
.byte $ff, $ff, $ff
.byte $ff, $ff, $ff
.byte $ff, $ff, $ff
.byte $ff, $ff, $ff
.byte $ff, $ff, $ff
.byte $ff, $ff, $ff
.byte $ff, $ff, $ff
.byte $ff, $ff, $ff
.byte $ff, $ff, $ff
.byte $ff, $ff, $ff
.byte $ff, $ff, $ff
.byte $ff, $ff, $ff
.byte $ff, $ff, $ff
.byte $ff, $ff, $ff
.byte $ff, $ff, $ff
.byte $ff, $ff, $ff
.byte $ff, $ff, $ff
.byte $ff, $ff, $ff
.byte $ff, $ff, $ff